### ISSUE TITLE
下载解压newAnno文件夹,这个newAnno是什么呢？

### ISSUE THREAD

**Issue by baolinhu** [Jeff-sjtu/labelKeypoint#1]
下载解压newAnno文件夹,问下这个newAnno是什么呢？谢谢

**Comment by jeffffffli** [comment]
你好， c93b1c35ee9267a13a9f70b25c9898337c7e7d7f 中，已添加示例链接

**Comment by baolinhu** [comment]
谢谢你的回答。可是那个示例链接打不开。如果你方便的话，可以发一份到我邮箱。hu_nobuone@163.com。
![image](https://user-images.githubusercontent.com/16516384/41189355-021a0f20-6bff-11e8-871f-8ea905e02f8e.png)
我放入coco的annotations和一些images，它会出现这样的错误
![image](https://user-images.githubusercontent.com/16516384/41189362-4027d25c-6bff-11e8-9494-3a0900733237.png)
如果有什么其他的关键点标记工具，可以给我推荐一下吗，实在没找到。谢谢。

**Comment by jeffffffli** [comment]
https://pan.baidu.com/s/1VkQD2FJ5t_pkrY6-SK8few 你可以尝试一下这个百度网盘链接。
coco的annotations需要处理一下才能使用，第一级的key并不是img_name。
其它关键点标记工具我也不了解，抱歉。

**Comment by baolinhu** [comment]
好的，谢谢您的帮助
