### ISSUE TITLE
How to annotate local data?

### ISSUE THREAD

**Issue by r1c7** [Jeff-sjtu/labelKeypoint#2]
How to use this tool to annotate local data at the beginning without 'anno.json'?
And how to modify these code according personal need, such as 2 keypoints or 14 keypoints?
Thanks!

**Comment by jeffffffli** [comment]
`anno.json` is used to draw bounding box in the image. If you want to annotate an image with unknown number of persons, you should modify the code about drawing bounding box.
If you want to label more keypoints, the code about the pop up buttons should be modified.
