### ISSUE TITLE
The COCO_anno cannot open and download in Google Drive

### ISSUE THREAD

**Issue by wangyarui** [Jeff-sjtu/labelKeypoint#3]
The COCO_anno cannot open and download in Google Drive..
```
抱歉，您无法访问此项目，因为它违反了我们的服务条款。
有关此主题的详细信息，请参阅 Google 云端硬盘帮助中心。
```
It is so appreciated and exciting if you can provide it for us, Thanks so much.

**Comment by jeffffffli** [comment]
Hi, the Google Drive link has been renewed in 0604cc527b2d03644283ab2f3a8466e43845702d.

**Comment by wangyarui** [comment]
@Jeff-sjtu Thanks very much, You are so kindhearted, hope you happy every day!Xixi~
